Iter2
northmule/gophkeeper pull request #2
Opened 2024-12-24 19:45 UTC by northmule

2025-01-11 01:51 UTC, vokinneberg approved these changes
Ну вот мы и подобрались к финальному выпускному проекту! 🎉 По традиции поздравляю с первым ревью, желаю удачи 🍀 Хочу отметить высокий уровень реализации проекта, продуманы многие моменты и в целом проект очень зрелый уже на первой итерации. Код хорошо структурирован, задокументирован и покрыт тестами. В принципе замечаний минимальное количество, тем не менее ниже я отмечу сильные стороны твоего PR, а также сделаю несколько комментариев по поводу того, на что стоит обратить внимание и что можно улучшить. 🤓 

**Сильные стороны твоего PR:**

- У тебя отличный процент покрытия на проекте! 🙌
- Спасибо за реализацию [[README.md](http://readme.md/)](http://readme.md/) файла с пояснением! 👍
- Структура проекта достаточно консистентная, понятная и лаконичная.
- Ты добавил документацию методов. 👍

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

- Для того чтобы сделать README немного более содержательным, я бы рекомендовал структурировать его следующим образом:
    - Можно добавить раздел с описанием сервиса и его базовой функциональности.
    - Добавить беджи с тестовым покрытием (это есть) и https://goreportcard.com/
    - Добавить раздел с подробным описанием того, как запускать сервис. Сюда может входить описание выполнения миграций БД, установки флагов или переменных окружения и так далее.
    - Раздел с описанием того, как тестировать сервис.
    - Раздел с описанием того, какие сторонние пакеты использовались для реализации с их версиями.
- Большинство тестов было бы удобно реализовать в качестве табличных тестов.
- Я не очень вижу смысл в создании слоёв, которые ничего по сути не делают. Возможно, в случае manager это частично оправдано, так как вызывается `util`, но вообще у этого слоя как будто нет никакой функции — по сути он только усложняет структуру программы. Стоит избавиться от слоёв-прокси.
- Не стоит паниковать во внутреннем компоненте - это приведёт к выходу из приложения. Лучше вернуть ошибку, если это возможно.
- Рекомендую всё же попробовать реализовать интерфейсы на стороне пользователя.
- Не совсем понимаю в чем приемущество использования паттерна Manager. Готов на эту тему подискутировать 😊
- Я бы добавить флаг, который управлял бы запуском миграций так как это не всегда может быть нужно.

2025-01-11 01:51 UTC, vokinneberg commented on internal/client/view/view.go
> +	cryptService, err := service.NewCrypt(v.cfg)
Я бы все-таки советовал передавать зависимости в `NewClientView(...)` и собирать дерево зависимостей в main, в этом View можно было бы использовать интерфейсы.

2025-01-11 01:51 UTC, vokinneberg commented on internal/client/config/config.go
> +func (c *Config) Init() error {
Судя по кейсу использования `Init()` его вполне можно было бы объединить с `NewConfig()`.

2025-01-11 01:51 UTC, vokinneberg commented on internal/client/config/config_test.go
> +	validConfig := `
Кажется, тут есть три кейса. Можно было бы попробовать реализовать табличные тесты.

2025-01-11 01:51 UTC, vokinneberg commented on internal/client/controller/authentication.go
> +	}
Кажется, что второй случай является подмножеством первого:
```suggestion
	if response.StatusCode != http.StatusOK {
		if response.StatusCode == http.StatusUnauthorized {
		    return nil, fmt.Errorf("не верная пара логин/пароль")
	        }
		return nil, fmt.Errorf("не известная ошибка")
	}
```

2025-01-11 01:51 UTC, vokinneberg commented on internal/client/controller/authentication_test.go
> +	_, err = authController.Send("unauthorizeduser", "unauthorizedpass")
Мне кажется здесь тоже было бы удобнее попробовать реализовать табличные тесты.

2025-01-11 01:51 UTC, vokinneberg commented on internal/client/controller/card_data.go
> +	}
Так же можно проверять вложенные кейсы:
```suggestion
	if response.StatusCode != http.StatusOK {
		if response.StatusCode == http.StatusUnauthorized {
		    return nil, fmt.Errorf("вы не авторизованы")
	        }
	        if response.StatusCode == http.StatusBadRequest {
		   return nil, fmt.Errorf("ошибка в запросе")
	        }
		return nil, fmt.Errorf("не известная ошибка")
	}
```

2025-01-11 01:51 UTC, vokinneberg commented on internal/client/controller/card_data_test.go
> +	t.Run("ok", func(t *testing.T) {
Как развитие идеи мне кажется здесь тоже было бы удобнее попробовать реализовать табличные тесты.

2025-01-11 01:51 UTC, vokinneberg commented on internal/client/service/crypt.go
> +func (crypt *Crypt) EncryptRSA(data []byte) ([]byte, error) {
Я не очень вижу смысл в создании слоёв, которые ничего по сути не делают. Возможно, в этом случае это частично оправдано, так как вызывается `util`, но вообще у этого слоя как-будто нет никакой функции — по сути он только усложняет структуру программы. Стоит избавиться от слоёв-прокси.

2025-01-11 01:51 UTC, vokinneberg commented on internal/client/service/crypt_test.go
> +		panic(err)
Не стоит паниковать во внутреннем компоненте - это приведет к выходу из приложения. Лучше вернуть ошибку, если это возможно. Даже в тесте это не оправдано.

2025-01-11 01:51 UTC, vokinneberg commented on internal/client/storage/memory.go
> +type Storage interface {
Рекомендую все же попробовать реализовать интерфейсы на стороне пользователя.

2025-01-11 01:51 UTC, vokinneberg commented on internal/server/storage/session.go
> +	mx     sync.RWMutex
👍 за использование RWMutex.

2025-01-11 01:51 UTC, vokinneberg commented on internal/server/services/access/access.go
> +type AccessService interface {
Здесь так же рекомендую все же попробовать реализовать интерфейсы на стороне пользователя.

2025-01-11 01:51 UTC, vokinneberg commented on internal/server/repository/repository.go
> +type Manager struct {
Не совсем понимаю в чем приемущество использования такого паттерна. Готов на эту тему подискутировать 😊

2025-01-11 01:51 UTC, vokinneberg commented on internal/server/api/handlers/card_data.go
> +	if request.UUID == "" { // новые данные
Кажется тут можно было бы использовать `else`, а еще лучше убрать разные ветки в отдельные функции так как они очень большие.

2025-01-11 01:51 UTC, vokinneberg commented on cmd/server/main.go
> +	migrations := db.NewMigrations(store.RawDB)
Я бы добавить флаг, который управлял бы запуском миграций так как это не всегда может быть нужно.

2025-01-11 01:51 UTC, vokinneberg commented on internal/server/api/handlers/routes.go
> +			r.With(
А можно эти middleware навесить на группу маршрутов для того чтобы не выполнять множество раз один и тот же код?

2025-01-11 01:51 UTC, vokinneberg commented on internal/server/api/handlers/item_data.go
> +	if owner.DataType == data_type.CardType {
Здесь можно попробовать использовать `switch-case`.

2025-01-11 01:51 UTC, vokinneberg commented on internal/server/api/handlers/registration.go
> +	return nil
Нам точно нужен этот пусто метод?

2025-01-11 01:52 UTC, vokinneberg requested changes
Ну вот мы и подобрались к финальному выпускному проекту! 🎉 По традиции поздравляю с первым ревью, желаю удачи 🍀 Хочу отметить высокий уровень реализации проекта, продуманы многие моменты и в целом проект очень зрелый уже на первой итерации. Код хорошо структурирован, задокументирован и покрыт тестами. В принципе замечаний минимальное количество, тем не менее ниже я отмечу сильные стороны твоего PR, а также сделаю несколько комментариев по поводу того, на что стоит обратить внимание и что можно улучшить. 🤓 

**Сильные стороны твоего PR:**

- У тебя отличный процент покрытия на проекте! 🙌
- Спасибо за реализацию [[README.md](http://readme.md/)](http://readme.md/) файла с пояснением! 👍
- Структура проекта достаточно консистентная, понятная и лаконичная.
- Ты добавил документацию методов. 👍

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

- Для того чтобы сделать README немного более содержательным, я бы рекомендовал структурировать его следующим образом:
    - Можно добавить раздел с описанием сервиса и его базовой функциональности.
    - Добавить беджи с тестовым покрытием (это есть) и https://goreportcard.com/
    - Добавить раздел с подробным описанием того, как запускать сервис. Сюда может входить описание выполнения миграций БД, установки флагов или переменных окружения и так далее.
    - Раздел с описанием того, как тестировать сервис.
    - Раздел с описанием того, какие сторонние пакеты использовались для реализации с их версиями.
- Большинство тестов было бы удобно реализовать в качестве табличных тестов.
- Я не очень вижу смысл в создании слоёв, которые ничего по сути не делают. Возможно, в случае manager это частично оправдано, так как вызывается `util`, но вообще у этого слоя как будто нет никакой функции — по сути он только усложняет структуру программы. Стоит избавиться от слоёв-прокси.
- Не стоит паниковать во внутреннем компоненте - это приведёт к выходу из приложения. Лучше вернуть ошибку, если это возможно.
- Рекомендую всё же попробовать реализовать интерфейсы на стороне пользователя.
- Не совсем понимаю в чем приемущество использования паттерна Manager. Готов на эту тему подискутировать 😊
- Я бы добавить флаг, который управлял бы запуском миграций так как это не всегда может быть нужно.

2025-01-13 06:44 UTC, northmule commented on internal/server/api/handlers/registration.go
> +	return nil
Тут необходимость пустых методов в том что бы реализовывать интерфейс для Decode/Encode  данных при помощи github.com/go-chi/render, который по сути является обёрткой скрывающей дополнительный код. Но при необходимости можно дописать и доп. логику в эти методы.

2025-01-14 14:57 UTC, northmule commented on internal/client/service/crypt.go
> +func (crypt *Crypt) EncryptRSA(data []byte) ([]byte, error) {
Здесь у меня попытка вынести общую логику для server и client в отдельный common механизм. С другой стороны можно сделать общий сервис, тогда метод-прослойку можно было бы удалить.

2025-01-14 15:01 UTC, northmule commented on internal/server/repository/repository.go
> +type Manager struct {
В итоге разделил manager на разные части, но в ущерб тестам. В клиенте подобный паттерн оставил как есть.

2025-01-14 15:10 UTC, northmule commented on internal/server/api/handlers/item_data.go
> +	if owner.DataType == data_type.CardType {
В каких случаях в GO предпочтительнее использовать конструкции switch-case или это больше дело вкуса?
В некоторых языках почему-то стараются избегать switch-case и используют if else или if elseif else

2025-01-16 03:46 UTC, vokinneberg approved these changes
Поздравляю с завершением выпускного проекта! 🙌 Ты проделал большую работу на курсе, и я очень рад видеть, что твой уровень владения Go значительно повысился 👍 Желаю удачи в дальнейшем применении знаний 🍀

- Спасибо за доработку [[README.md](http://readme.md/)](http://readme.md/) файла! 👍
- Ты значительно оптимизировал инициализацию роутеров! 👍
- Здорово, что ты попробовал поработать над переосмыслением интерфейсов! Единственное замечание в именовании, например `OwnerCRUD` похож на репозиторий, так что я рекомендовал бы его назвать `OwnerRepo`. Вообще, мне намного больше нравится новая реализация, потому что вот такие вызовы `h.manager.TextData()` выглядели немного избыточно.

2025-01-16 05:50 UTC, merged